spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.tedu.springcloud.enties
  mapper-locations: 
  - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: cn.tedu-microservicecloud-springcloudconfig01
  company.name: www.smartisan.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.tedu.springcloud.enties
  mapper-locations: 
  - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: cn.tedu-microservicecloud-springcloudconfig01
  company.name: www.smartisan.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
      
  